### ISSUE TITLE
More idempotency for chef_dk providers

### ISSUE THREAD

**Issue by leftathome** [RoboticCheese/chef-dk-chef#16]
Great cookbook!  Installs chef-dk on every run, though.  Need a platform-specific implementation of load_current_resource(), I think.

(Witnessed on OS X so far but based on reading the code I expect it's the same on other platforms)

**Comment by RoboticCheese** [comment]
Going to close this out since OS X was fixed and relying on inline resources' own idempotence checks seems to be the preferred pattern for library cookbooks nowadays.
