### ISSUE TITLE
windows support broken

### ISSUE THREAD

**Issue by joelwilson** [RoboticCheese/chef-dk-chef#49]
I believe that [commit 5e041dedd](https://github.com/RoboticCheese/chef-dk-chef/commit/5e041deddcbbb04330103c8b72c734b5ce22b69b#diff-1541a0580bb9a01a2fbd1d7e6777e524R64) broke support for Windows. Instead of conditionally calling the `global_shell_init` method if the attribute is set (true), the method is always called. Ultimately, that calls `bashrc_file` which is overridden in the windows provider to [return `fail`](https://github.com/RoboticCheese/chef-dk-chef/blob/master/libraries/provider_chef_dk_windows.rb#L60).

**Comment by RoboticCheese** [comment]
Happily, this can be tested for real now that Windows support for Test Kitchen was released. The fix (#50) has been merged and will be in the next release.
