### ISSUE TITLE
Support for installation of chef gems.

### ISSUE THREAD

**Issue by sernapallyanurag** [RoboticCheese/chef-dk-chef#64]
How can I automate installation of
``knife-azure, mongo etc.,``

**Comment by RoboticCheese** [comment]
There's no custom resource in this cookbook for that, but there is a `gem_binary` property on the [gem_package](https://docs.chef.io/resource_gem_package.html) resource. So it sounds like you'd be able to do something like:

```
gem_package 'knife-azure' do
  gem_binary '/opt/chefdk/embedded/bin/gem'
end
```

**Comment by sernapallyanurag** [comment]
Thank You.
